name: Build and deploy HTML documentation
on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - name: Prerequisites
          run: sudo apt install doxygen

        - name: Configure
          run: cmake . -B build/ -DORION_BUILD_CORE=OFF

        - name: Build
          run: cmake --build build/
            && cd build/docs/html
            && touch .nojekyll

        - name: Deploy
          uses: JamesIves/github-pages-deploy-action@releases/v4
          with:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            BRANCH: gh-pages
            FOLDER: build/docs/html
