name: Build HTML documentation
on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v3

        - name: Prerequisites
          run: sudo apt update
            && sudo apt install doxygen

        - name: Configure
          run: cmake . -B build/ -DORION_BUILD_CORE=OFF

        - name: Build
          run: git switch gh-pages

        - name: Deploy
          uses: JamesIves/github-pages-deploy-action@releases/v3
          with:
            GITHUB_TOKEN: ${{ github.token }}
            BRANCH: gh-pages
            FOLDER: build/docs/html

        - name: Delete workflow runs
          uses: Mattraks/delete-workflow-runs@v2
          with:
            token: ${{ github.token }}
            repository: ${{ github.repository }}
            retain_days: 0
            keep_minimum_runs: 0
