name: Build HTML documentation
on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v3

        - name: Install dependencies
          run: sudo apt install graphviz doxygen

        - name: Generate Doxyfile
          run: cmake . -B build/ -DORION_BUILD_CORE=OFF

        - name: Build HTML documentation
          run: cd .github/workflows
            && chmod +x doxygen
            && ./doxygen ../../build/docs/Doxyfile

        - name: Deploy
          uses: JamesIves/github-pages-deploy-action@releases/v3
          with:
            GITHUB_TOKEN: ${{ github.token }}
            BRANCH: gh-pages
            FOLDER: build/docs/html
