name: Build HTML documentation
on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v3

        - name: Prerequisites
          run: sudo apt install doxygen

        - name: Configure
          run: cmake . -B build/ -DORION_BUILD_CORE=OFF

        - name: Build
          run: cmake --build build/
            && cd build/docs/html
            && touch .nojekyll
            
        - name: Doxygen Action
          uses: mattnotmitt/doxygen-action@1.9.1
          with:
            doxyfile-path: 'build/docs/Doxyfile'
            working-directory: 'build/docs'

        - name: Deploy
          uses: JamesIves/github-pages-deploy-action@releases/v3
          with:
            GITHUB_TOKEN: ${{ github.token }}
            BRANCH: gh-pages
            FOLDER: build/docs/html
